# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a614efb2f041fc499de8aa290019d2fc72ae91d2acf6601af784dacce93242b1ac23c0cd74e51ebc47b25f3357a0da4d49ff9ee524caa19147b05f4ec36aa1d7

test:
  secret_key_base: eeba65fadcccbb059ddb54c93c037795c0aa34481fa8131e97fa09340e2177710942874bcd0f430ffa35bf72a3cd1053037dac389eeca88b5dd878a468962801

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
